# cloudProvider can be aws/gcp
cloudProvider:

# Unique ID for the POD 
# recommended convension: 
# <Environment Type>-<customerID>-<FeedID>-<HeadendID>-<POD Type>
# POD type can be : player, switcher, dd
# Environment type can be: production, test, devQA, staging etc
# Eg: production-NBCU-HD1080i50-nbcu001-player
# ONLY lowercase albhabets and '-' are allowed.
## AWS Availability Zone
uuid:

# docker secret from cloudProvider
dockerSecret:

# required if cloudProvider is gcp
project:

# POD type
# It should always be set to dd
podType: dd

## AWS Availability Zone
availabilityZone:

# UUID of the peer POD to receive the input stream
peerInputUuid:
#
# UUID of the peer POD to deliver the stream
peerOutputUuid:

# UUID of the vpcpeer POD to receive the input stream
vpcPeerInputUuid:

# UUID of the vpcpeer POD to deliver the stream
vpcPeerOutputUuid:

# URL for peer output stream protocol
peerOutputProtocol:

# URL for public output stream protocol
publicOutputProtocol:

# URL for vpcpeer output stream protocol
vpcPeerOutputProtocol:

# URL for peer input stream protocol
peerInputProtocol:

# URL for public input stream protocol
publicInputProtocol:

# URL for vpcpeer input stream protocol
vpcPeerInputProtocol:

# Fluentd endpoint to push the logs
fluentdEndpoint:

# Name for the ingress controller
ingressControllerName:

# Name space for the ingress controller
ingressControllerNamespace:

#Configs for Doordarshan
doordarshanMemSize: 8Gi
doordarshanCpuSize: 4
doordarshanEbsSize: 50Gi

#Configs for TARDIS 
tardisMemSize: 1.5Gi
tardisCpuSize: 500m
tardisEbsSize: 25Gi
