name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        type: string
        required: true
        default: "Default messsage"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  from-dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Received message ${{ github.event.inputs.message }}"
          echo "Anothe way for message $MESSAGE"
        env:
          MESSAGE: ${{ inputs.message }}
