name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      messsage: 'Default message'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  from-dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Received message $MESSAGE"
        env:
          MESSAGE: ${{ inputs.message }}
