# Sample command to get workflow id
# curl -L \
#         -H "Accept: application/vnd.github+json" \
#         -H "Authorization: Bearer <GITHUB_TOKEN>" \
#         -H "X-GitHub-Api-Version: 2022-11-28" \
#         https://api.github.com/repos/tejasrinivask/test/actions/workflows
#
#
#
#
# Sample command to run the workflow through api call
# curl -L \
#         -X POST \
#         -H "Accept: application/vnd.github+json" \
#         -H "Authorization: Bearer <GITHUB_TOKEN>" \
#         -H "X-GitHub-Api-Version: 2022-11-28" \
#         https://api.github.com/repos/tejasrinivask/test/actions/workflows/73031903/dispatches \
#         -d '{"ref":"main","inputs":{"message":"Message from cURL"}}'

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        type: string
        required: true
        default: "Default messsage"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  from-dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Received message ${{ github.event.inputs.message }}"
          echo "Anothe way for message $MESSAGE"
        env:
          MESSAGE: ${{ inputs.message }}
