name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [test_result]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE

